# Generated by Django 3.1.7 on 2021-04-06 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contactpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactPage',
        ),
    ]
