# Generated by Django 3.1.7 on 2021-04-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='web',
            field=models.URLField(blank=True),
        ),
    ]
