# Generated by Django 3.1.7 on 2021-04-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
