# Generated by Django 3.1.7 on 2021-04-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0002_auto_20210401_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='color',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
