# Generated by Django 3.1.7 on 2021-04-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0003_pet_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
