# Generated by Django 3.1.7 on 2021-04-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caretakers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caretaker',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
