# Generated by Django 3.1.7 on 2021-04-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caretakers', '0002_auto_20210401_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='job_position',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
