# Generated by Django 3.1.7 on 2021-04-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_remove_found_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='found',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
