# Generated by Django 3.1.7 on 2021-04-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20210408_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='found',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
